name: playerix

services:
  db:
    image: mysql:8.0
    container_name: playerix-db
    restart: always
    env_file: .env
    ports:
      - "3307:3306"
    volumes:
      - playerix_mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: playerix-backend
    restart: always
    env_file: .env
    ports:
      - "3001:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: playerix-frontend
    restart: always
    ports:
      - "4201:80"
    depends_on:
      - backend

volumes:
  playerix_mysql_data:
